reference_models:
  - name: "google/codegemma-7b"
    api: "nvidia"
  - name: "meta/codellama-70b"
    api: "nvidia"
  - name: "mistralai/codestral-22b-instruct-v0.1"
    api: "nvidia"
  - name: "Replete-AI/Replete-Coder-Llama3-8B"
    api: "hugging_face"            
    
aggregator:
  - name: "deepseek-coder"
    api: "deepseek"
