reference_models:
  - name: "llama3-70b-8192"
    api: "groq"
    aggregator: True
  - name: "Qwen/Qwen1.5-72B-Chat"
    api: "together"
  - name: "google/gemma-2-9b-it"
    api: "deepinfra"
  - name: "gpt-4o-mini"
    api: "openai"  
  - name: "mistral-large-latest"
    api: "mistral"    
  - name: "upstage/solar-10.7b-instruct"
    api: "nvidia"
  - name: "deepseek-chat"
    api: "deepseek"    
  - name: "HuggingFaceTB/SmolLM-135M"
    api: "hugging_face"   
  - name: "claude-3-sonnet-20240229"
    api: "anthropic" 
  - name: "gemini-1.5-flash"
    api: "gemini"        