reference_models:
  - name: "command-r-plus"
    api: "cohere"    
    aggregator: True
  - name: "command-r"
    api: "cohere"
  - name: "command-light"
    api: "cohere"
  - name: "command-nightly"
    api: "cohere"            

    
